### ISSUE TITLE
Typescript only ?

### ISSUE THREAD

**Issue by DevSide** [hudochenkov/postcss-styled-syntax#12]
I'm coming from the stylelint doc, when I try to use your library i get: `Cannot find module 'typescript'`.

I can see the TS parser inside your code, is this a Typescript library only ?

**Comment by hudochenkov** [comment]
It works for JavaScript also. TypeScript in dependencies is because of a parser, which parses both JavaScript and TypeScript.

Could you create a reproduction repository?
