### ISSUE TITLE
Usage with VSCode plugin

### ISSUE THREAD

**Issue by timhettler** [hudochenkov/postcss-styled-syntax#16]
Hello, I am trying to get in-editor highlighting to work with [Stylelint VSCode](https://github.com/stylelint/vscode-stylelint) and this plugin. When I add `typescriptreact` to the  [`stylelint.validate`](https://github.com/stylelint/vscode-stylelint#stylelintvalidate) configuration, the entire file is checked, not just the styling blocks.

My stylelint config:
```
module.exports = {
  extends: [
    "stylelint-config-standard"
  ],
  customSyntax: "postcss-styled-syntax",
}
```

Please let me know if you have any advice on how to get in-editor linting to work!

**Comment by hudochenkov** [comment]
I don't use Stylelint VS Code extension. So I can't say anything for sure.

Stylelint does run on a whole file always. This package helps Stylelint identify styles blocks, and then Stylelint rules are run on these blocks.

Is there an error or an issue you're experiencing?

**Comment by timhettler** [comment]
I think I've managed to get this working. I had to manually add the custom syntax to the plugin settings (it wasn't able to infer from the `.stylelintrc` file). For anyone else with this problem, here are the workspace settings I edited:

```json
"stylelint.customSyntax": "postcss-styled-syntax",
"stylelint.validate": [
  "typescriptreact",
  "javascriptreact"
]
```

**Comment by hudochenkov** [comment]
I'm not sure what was the issues. Official Stylelint VS Code extension works without `"stylelint.customSyntax"` VS Code settings, if `customSyntax` is specified in the `.stylelintrc`. In initial message I don't see any issues.
