### ISSUE TITLE
Support for the css prop

### ISSUE THREAD

**Issue by kitajchuk** [hudochenkov/postcss-styled-syntax#17]
It seems the [css prop](https://styled-components.com/docs/api#css-prop) is not supported.

I am using bare bones setup found here:
https://styled-components.com/docs/tooling#for-stylelint-v15-recommended

I can verify that the `css` prop is not being supported here. It does work if you use the `css` function with the `css` prop but that is just redundant.

It would be quite nice to have this feature—is it possible to support this?

**Comment by hudochenkov** [comment]
I think technically it is possible to add support, but I'm not sure if it's a good idea. `css` prop in this form seems to be used only in styled-components library. And I have a feeling `css` props is not used that much. At least from my experience.

**Comment by kitajchuk** [comment]
> I think technically it is possible to add support, but I'm not sure if it's a good idea. `css` prop in this form seems to be used only in styled-components library. And I have a feeling `css` props is not used that much. At least from my experience.

Fair enough. Thanks for the reply.
