### ISSUE TITLE
Auto-fix not working and some issue can not be detected.

### ISSUE THREAD

**Issue by lashawty** [hudochenkov/postcss-styled-syntax#20]
Hi,
Thank you for helping me solve the previous issue 👍🏻

I've noticed the doc you mentioned about Parsing, my issue may be the problem you talked about:

<img width="895" alt="截圖 2023-09-18 上午10 50 21" src="https://github.com/hudochenkov/postcss-styled-syntax/assets/104483622/d1701ace-ac87-4dbd-b1c6-3af11479628b">

However, if I change my code to this, which will solve the issue, but the project structure is too big to fix the code like this 
```
${media.lg && css`
        margin-top: -30px;
        img {
            width: 50px;
            height: 50px;
        }
    `}
```

Is there any way I can custom my own syntax for detecting and auto-fixing?

Thanks again for the hard work, really looking forward to adding this feature 🥹

**Comment by hudochenkov** [comment]
Parser only knows about <code>css\`\`</code> helper. It doesn't know about <code>media.lg\`\`</code> or any other helper.

`css` is a common name among many CSS-in-JS libraries. All tools work with it. E.g., Prettier would also look inside <code>css\`\`</code>, but not inside <code>media.lg\`\`</code>.

I'm afraid there won't be any fix in this package, as it's a project specific issue.

**Comment by lashawty** [comment]
No worries, thanks again for your time.
