### ISSUE TITLE
Autofix not working when Interpolations exist

### ISSUE THREAD

**Issue by lashawty** [hudochenkov/postcss-styled-syntax#22]
<img width="1186" alt="截圖 2023-09-25 下午12 57 20" src="https://github.com/hudochenkov/postcss-styled-syntax/assets/104483622/fd5a753e-f2f7-4c00-a5f7-7d63e6b9bddc">

Hi, 
auto fix is not working in the context I mentioned in the screenshot above,
is there any way to fix this?

Thanks for your time again.

**Comment by hudochenkov** [comment]
I think this issues reported in the wrong repository. I would assume that it is about [`stylelint-order`](https://github.com/hudochenkov/stylelint-order). Then the answer is in the readme:

> CSS-in-JS styles with template interpolation [could be ignored by autofixing](https://github.com/hudochenkov/postcss-sorting#css-in-js) to avoid style corruption.

**Comment by lashawty** [comment]
Thanks for the remind.
