### ISSUE TITLE
Unexpected invalid media query

### ISSUE THREAD

**Issue by shanpig** [hudochenkov/postcss-styled-syntax#32]
interpolation of ThemeProvider or other imported constants are not supported in the current postcss-styled-syntax. However, it is supported in normal styling.

<img width="1206" alt="Screenshot 2024-06-26 at 9 59 22 AM" src="https://github.com/hudochenkov/postcss-styled-syntax/assets/31932700/d29d2a64-2475-412b-a71d-6725ff0d7782">

**Comment by hudochenkov** [comment]
This is a Stylelint rule issue. Report in their repository, please.

**Comment by shanpig** [comment]
Seems like [stylelint doesn't regard this as their issue](https://github.com/stylelint/stylelint/issues/7816) either 😢
