### ISSUE TITLE
Support React Inline Styles (JSX)

### ISSUE THREAD

**Issue by rakleed** [hudochenkov/postcss-styled-syntax#34]
Can you add support for [React Inline Styles (JSX)](https://react.dev/reference/react-dom/components/common#:~:text=suppressing%20hydration%20errors.-,style,-%3A%20An%20object%20with)?

```html
<button style={{ border: 'none' }}>Download</button>
```

Or is it outside the scope of your plugin?

**Comment by hudochenkov** [comment]
It is outside of the scope of the package. This package is only for template literals.
